// Copyright (c) 2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 2.5.0 to release 2.6.0

== Inter-service communication - Ribbon

Ribbon was used by our Feign client that lets business services get information on the current user from the Users
service.

Ribbon is no longer maintained, so we chose to remove it from our dependencies (mostly because it was blocking any
update of the other Spring dependencies).

Instead, the Feign client now relies on an external property to know where the Users service can be reached, and there
is no load-balancing for now.

This requires a change to service configuration: the `users.ribbon.listOfServers` property should be removed and
replaced with `operatorfabric.servicesUrls.users`.

It should be set in the configuration of all business services (except users), or in the common configuration.

.Example
[source,yaml]
----
operatorfabric:
  servicesUrls:
    users: "http://localhost:2103"
----

According to the Feign documentation, the property should contain "an absolute URL or resolvable hostname (the protocol
is optional)".

IMPORTANT: This property is mandatory, if it is absent the application won't start.

IMPORTANT: While the ribbon property could handle an array of several urls, this new property expects a single url as
there is no load-balancing mechanism for now.

== Management of visible menus

The visibility of some core OperatorFabric menus (monitoring, logging, feed configuration screen,...) was so far
configurable for a given OperatorFabric instance through various properties in `web-ui.json`.

As of this version, it has been unified with that of custom menus:

* It will now be managed in `ui-menu.json` along with custom menus
* It is now possible to make these menus visible only for certain groups

.Deprecated properties in `web-ui.json`
* `navbar.hidden` (array of menus to hide)
* `admin.hidden` (boolean)
* `feedConfiguration.hidden` (boolean)
* `realTimeUsers.hidden` (boolean)
* `settings.nightDayMode` (boolean)

.New property in `ui-menu.json`
[source,json]
----
{
  "coreMenusConfiguration":
  [
    {
      "id": "coreMenuId1",
      "visible": true
    },
    {
      "id": "coreMenuId2",
      "visible": false
    },
    {
      "id": "coreMenuId3",
      "visible": true,
      "showOnlyForGroups": ["ADMIN","SOME_OTHER_GROUP"]
    }
  ]
}
----

All core menus should be listed under this new `coreMenusConfiguration` property in `ui-menu.json`, each with their own
`visible` and (optionally) `showOnlyForGroups` property.

Necessary actions for the migration:

* Remove the deprecated properties listed above from your `web-ui.json`
* Add a `coreMenusConfiguration` block to your `ui-menu.json` (see the
ifdef::single-page-doc[<<core_menu_config, documentation>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#core_menu_config, documentation>>]
for details and a full example)